# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: '목차'
  items:
    - label: '안드로이드 기본 구성 요소 정리'
      link: '/usage/01-android'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: Community
  items:
    - label: '네이버 카페'
      link: https://cafe.naver.com/teamcadi
